# Generated by Django 6.0.2 on 2026-05-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_favoritejobs_region_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
    ]
