# Generated by Django 6.0.2 on 2026-05-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Verified by the admin'),
        ),
    ]
