# Generated by Django 6.0.2 on 2026-03-03 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/profiles/%Y/%m/', verbose_name='Picture')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified Account')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra Data')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_dark_mode',
            field=models.BooleanField(default=False, verbose_name='dark mode'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='preferred language'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Role Name')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='Role Key/Code')),
                ('description', models.TextField(blank=True, help_text="A brief description of this role's permissions", null=True, verbose_name='Description')),
                ('is_identity', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='Does a member of this role need administrative approval before activating their account?', verbose_name='Require Approval')),
                ('view_in_register', models.BooleanField(default=False, verbose_name='Show in Register')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_identity': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_users', to='accounts.role', verbose_name='Identity type'),
        ),
    ]
