# Generated by Django 6.0.2 on 2026-03-03 02:00

from django.db import migrations
from django.conf import settings


def create_roles(apps, schema_editor):
    # جلب موديل Role من داخل المهاجرات لضمان استقرار الحالة
    Role = apps.get_model('accounts', 'Role')

    # جلب قائمة الأدوار من settings.py
    # إذا لم تكن SITE_ROLES موجودة، سيتم استخدام قائمة فارغة لتجنب الخطأ
    roles_list = getattr(settings, 'SITE_ROLES', [])

    for role_data in roles_list:
        # استخدام update_or_create يضمن:
        # 1. إنشاء الدور إذا لم يكن موجوداً (بناءً على الكود الفريد code)
        # 2. تحديث بيانات الدور إذا كان موجوداً مسبقاً (لتعديل المسميات أو الصلاحيات)
        Role.objects.update_or_create(
            code=role_data.get('code'),
            defaults={
                'name': role_data.get('name'),
                'is_identity': role_data.get('is_identity', True),
                'requires_approval': role_data.get('requires_approval', False),
                'view_in_register': role_data.get('view_in_register', True),
            }
        )


class Migration(migrations.Migration):
    dependencies = [
        # تأكد أن هذا الاعتماد يشير للملف السابق له مباشرة (مثلاً 0003)
        ('accounts', '0002_profile_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]



#
# def create_roles(apps, schema_editor):
#     Role = apps.get_model('accounts', 'Role')
#     # إضافة الأدوار الأساسية
#     Role.objects.get_or_create(
#         name='user',
#         code='user',
#         is_identity=True,
#         requires_approval=False,
#         view_in_register=True,
#     )
#
#     Role.objects.get_or_create(
#         name='company',
#         code='company',
#         is_identity=True,
#         requires_approval=True,
#         view_in_register=True,
#      )
#     Role.objects.get_or_create(
#         name='student',
#         code='student',
#         is_identity=True,
#         requires_approval=True,
#         view_in_register=False,
#      )
#
# class Migration(migrations.Migration):
#     dependencies = [
#         ('accounts', '0002_profile_alter_customuser_options_and_more'), # تأكد أن هذا اسم المهاجرة السابقة عندك
#     ]
#     operations = [
#         migrations.RunPython(create_roles),
#     ]
