# Generated by Django 6.0.2 on 2026-03-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_first_name_and_more'),
        ('accounts', '0004_seed_roles'),
    ]

    operations = [
    ]
