"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import environ
import shutil
from pathlib import Path
from django.utils.translation import gettext_lazy as _



# =====================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# =====================================================================
# << env >>
# =====================================================================

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env')) # . قراءة ملف .env

APP_NAME=env('APP_NAME')
SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=False)
EMAIL_SERVICE = env('EMAIL_SERVICE', default='console')
ALLOWED_HOSTS = []
# ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
# =======================[get npm path from system ]=====================

# يبحث النظام عن مكان npm تلقائياً
NPM_BIN_PATH = shutil.which("npm") or shutil.which("npm.cmd")

# إذا لم يجده (في حالات نادرة على ويندوز)، نضع المسار الاحتياطي
if DEBUG and not NPM_BIN_PATH:
    NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

# =====================================================================

TAILWIND_APP_NAME = 'theme'



# =====================================================================
# << Applications Definition >>
# =====================================================================
INSTALLED_APPS = [

    "unfold",  # <-- يجب أن تكون هنا في البداية
    "unfold.contrib.filters",
    "unfold.contrib.forms",

    # 1. تطبيقات Django الأساسية (يجب أن تكون في القمة دائماً)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # ضروري جداً لـ allauth

    # 4. تطبيقاتك البرمجية الخاصة
    'accounts',
    'core',

    # === [AUTO_GENERATED_APPS_START] ===
    'members',
    'companies',
    # === [AUTO_GENERATED_APPS_END] ===

    # 2. تطبيقات Allauth (يجب أن تأتي بعد تطبيقات Django الأساسية)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',

    # 3. تطبيقات التنسيق (Crispy & Tailwind)
    'crispy_forms',
    'crispy_tailwind',
    'tailwind',
    'theme',  # تطبيق الثيم الخاص بك

    # 5. الأدوات الإضافية
    'django_browser_reload',
    "django_htmx",
    'widget_tweaks',
    'django.contrib.humanize',

]

# =====================================================================
# << UNFOLD >>
# =====================================================================

UNFOLD = {
    "SITE_TITLE": f"{APP_NAME} Control Panel",
    "SITE_SYMBOL": "settings", # أيقونة من Google Fonts
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "500": "168 85 247", # لون بنفسجي جذاب مثلاً
            "600": "147 51 234",
            "900": "88 28 135",
        },
    },
}


SITE_ID = 1

# =====================================================================
# << Middleware >>
# =====================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    "django_htmx.middleware.HtmxMiddleware",

    'core.middleware.ApprovalCompanyMiddleware',
]



# =====================================================================
# << Templates & Components >>
# =====================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'companies.context_processors.stats_processor',
                'members.context_processors.stats_processor',

            ],

            'libraries': {
                'ui_components': 'core.templatetags.ui_components',
            },
            'builtins': [

                'django.templatetags.i18n', # 1. مكتبة الترجمة (عالمية)
                # 'django.templatetags.static',# 2. مكتبة الملفات الثابتة (عالمية لـ CSS/JS)
                'core.templatetags.ui_components', # مكتبة تحميل المكونات القابلة لإعادة الاستخدام
            ],
        },
    },
]

# =====================================================================
# << Routers >>
# =====================================================================

ROOT_URLCONF = 'config.urls' # ملف التوجيه الافتراضي  للموقع والذي يبداء الانطلاق منه
WSGI_APPLICATION = 'config.wsgi.application'
DEFAULT_HOME_URL = 'core:home'

# =====================================================================================
# << Database >>
# =====================================================================================


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# =====================================================================================
# << Internationalization >>
# =====================================================================================


# =====================================================================================
# << Local Languages >>
# =====================================================================================

LANGUAGE_CODE = 'ar' #'en-us' # اللغة الافتراضية

TIME_ZONE = 'Asia/Riyadh' # أو التوقيت المحلي لليمن 'Asia/Aden'
USE_I18N = True
USE_L10N = True # لضمان تنسيق الأرقام والتواريخ محلياً
USE_TZ = True
# قائمة الغات  المتاحة لترجمة
LANGUAGES = [
    ('ar', _('Arabic')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]
LANGUAGE_SELECT_FROM_BROWSER = False
LANGUAGE_COOKIE_NAME = 'django_language'
# ====================================================================================
# << Static Files >>
# =====================================================================================

# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# مسار حفظ الوسائط
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# =====================================================================================
# << Auth Settings >>
# =====================================================================================

# ACCOUNT_FORMS = {
#     'signup': 'accounts.forms.CustomSignupForm',
# }

LOGIN_URL = 'account_login'  # الرابط الذي يتم توجيه المستخدم إليه إذا حاول دخول صفحة محمية وهو غير مسجل
AUTH_USER_MODEL = 'accounts.CustomUser' # تحديد الModel المعتمد لحساب المستخدم في المشروع
LOGIN_REDIRECT_URL = 'accounts:redirect_by_role' #  التوجيه بناءً على "الهوية"
LOGOUT_REDIRECT_URL = 'core:home' # الرابط الذي سيتم الانتقال إليه بعد تسجيل الخروج

ACCOUNT_USERNAME_REQUIRED = False # التأكد من أن allauth لا يبحث عن username
ACCOUNT_AUTHENTICATION_METHOD = "email" # يمكن للمستخدم الدخول عبر الإيميل بدلاً من اليوزر نيم
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True


# << Password Validation Settings>>
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# =============================================================
# Email sending settings using Gmail SMTP
# =============================================================

"""
- mandatory: تجبر المستخدم على التحقق قبل الدخول
- optional: يرسل بريداً لكن لا يمنعه من الدخول
- none: لا يرسل بريداً
"""
ACCOUNT_EMAIL_VERIFICATION = "optional" # اختياري رابط التحقق

if EMAIL_SERVICE == 'smtp':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # convert from console to SMTP
    EMAIL_HOST = 'smtp.gmail.com'  # Gmail's SMTP server
    EMAIL_PORT = 587  # Port used to send mail via TLS
    EMAIL_USE_TLS = True  # Enable TLS encryption to protect the connection with the Gmail server
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')  # The email address the application uses to connect to the mail server
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')  # Mail server password (App Password)
    DEFAULT_FROM_EMAIL = f'{APP_NAME} | Support <{EMAIL_HOST_USER}>'  # The default sender name that will appear in the messages
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# =====================================================================================
# << Identity Roles >>
# =====================================================================================

# create identity roles in your website

SITE_ROLES = [
    {
        'code': 'member',
        'name': 'member',
        'app_name': 'members',
        'domain': 'gmail',
        'is_identity': True ,
        'requires_approval': False,
        'view_in_register': True,
    },
    {
        'code': 'company',
        'name': 'company',
        'app_name': 'companies',
        'domain': 'company',
        'is_identity': True,
        'requires_approval': True,
        'view_in_register': True
    },
]

#  Linking roles to their respective control panels

ROLE_DASHBOARDS = {
    role['code']: f"{role['app_name']}:dashboard"
    for role in SITE_ROLES
    if role.get('is_identity') and 'app_name' in role
}

# إضافة رابط الأدمن الافتراضي لـ Django
ROLE_DASHBOARDS['admin'] = 'admin:index'


# ROLE_DASHBOARDS = {
#     role['code']: (
#         'admin:index' if role['code'] == 'admin'
#         else f"{role['code']}s:dashboard"
#     )
#     for role in SITE_ROLES
# }

# =====================================================================================
# << Settings Crispy Forms >>
# =====================================================================================
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"


# =====================================================================================
# << Errors Pages >>
# =====================================================================================
handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

# if not DEBUG:
#     # إجبار الاتصال عبر HTTPS
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
#
#     # حماية المتصفح من هجمات XSS
#     SECURE_BROWSER_XSS_FILTER = True
#     SECURE_CONTENT_TYPE_NOSNIFF = True
#
#     # حماية الاستجابة (HSTS) - تذكر ضبطها بحذر
#     SECURE_HSTS_SECONDS = 31536000
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True