# Generated by Django 6.0.2 on 2026-04-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='السعودية', max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, help_text='Preferably 512x512 pixels', null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الوظيفة')),
                ('description', models.TextField(verbose_name='الوصف الوظيفي')),
                ('requirements', models.TextField(verbose_name='المتطلبات')),
                ('location', models.CharField(default='الرياض', max_length=100)),
                ('employment_type', models.CharField(choices=[('full-time', 'دوام كامل'), ('part-time', 'دوام جزئي'), ('remote', 'عن بعد'), ('contract', 'عقد')], default='full-time', max_length=50)),
                ('experience_level', models.CharField(choices=[('entry', 'مبتدئ'), ('mid', 'متوسط خبرة'), ('senior', 'خبير')], default='mid', max_length=20)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.skillcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.companyprofile')),
                ('required_skills', models.ManyToManyField(related_name='required_skills', to='core.skill')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول مبدئياً'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.job')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='members.memberprofile')),
            ],
            options={
                'unique_together': {('job', 'member')},
            },
        ),
    ]
