# Generated by Django 6.0.2 on 2026-04-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_job_category_alter_job_title_and_more'),
        ('core', '0002_country_favoritejobs_region_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.city'),
        ),
    ]
