# Generated by Django 6.0.2 on 2026-05-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_job_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
    ]
