# Generated by Django 6.0.2 on 2026-04-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='avater',
            field=models.ImageField(blank=True, help_text='Preferably 512x512 pixels', null=True, upload_to='members/avaters/', verbose_name='Avater'),
        ),
    ]
