# Generated by Django 6.0.2 on 2026-04-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0002_memberprofile_avater'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='core.skill'),
        ),
    ]
