# Generated by Django 6.0.2 on 2026-04-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0003_memberprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills', to='core.skill'),
        ),
    ]
