# Generated by Django 6.0.2 on 2026-05-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_memberprofile_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
